name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: test and build
      run: |
        npm install
        npm run test
        npm run build
    - name: NPM publish if not present
      uses: romainseb/action-npm-publish-if-not-present@0.0.2
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

